print("こんにちわ")
print("今日は何日？")
my_day = input()
print ("今日は" + my_day + "日だったね！")
print ("明日は" + str(int(my_day)+1) + "日だね")
print("ところでお名前は？")
my_name = input()
print("あなたの名前は " + str(len(my_name)) +  "文字ですね")
